version: '2'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file: common.env
    depends_on:
      - db
      - redis

  db:
    image: library/postgres:11.1-alpine
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - app-db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app

  redis:
    image: library/redis:5.0-alpine
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - app-redis:/data

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    command: celery -A app worker --app=app.celeryconf:app --loglevel=info
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file: common.env
    depends_on:
      - redis

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local

networks:
  saleor-backend-tier:
    driver: bridge
