# Generated by Django 2.2.4 on 2019-12-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_order_gift_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='language_code',
            field=models.CharField(default='ko', max_length=35),
        ),
    ]
